### PR TITLE
remove flag for string and make it an arg

### PR DESCRIPTION
**Pull request by slashformotion**

### CODE REVIEW

**Comment by slashformotion** [comment]
@sansyrox is there any chance this can be merged?

**Comment by sansyrox** [comment]
Hey @slashformotion 👋 

Thank you for the PR. I just missed this PR when you made it 😅 

Since this PR changes the behavior of the crate, could you alter the README as well? With the new invocation?

**Comment by slashformotion** [comment]
I don't have the time right now, I will work on it in february

**Comment by slashformotion** [comment]
Here is the update

**Comment by sansyrox** [comment]
Thank you @slashformotion . Having a look!

**Review by sansyrox — APPROVED** [review]
LGTM! Great work @slashformotion ✨

**Pull request merged**
